version: '3.8'

services:
  postgres:
    image: postgres:14.6
    restart: always
    ports:
      - '5432:5432'
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=account_microservices
      - POSTGRES_USER=microservicestest
      - POSTGRES_PASSWORD=microservicestest
      - POSTGRES_PORT=5432

